/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projecttubesstrukturdatasiapraja.View.Siswa;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Pongo
 */
public class DashboardSiswaView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardSiswa
     */
    public DashboardSiswaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnPengajuanPkl = new javax.swing.JButton();
        jBtnAbsensi = new javax.swing.JButton();
        jBtInformasi = new javax.swing.JButton();
        jBtnLogout = new javax.swing.JButton();
        jLabelSelamatDatang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnPengajuanPkl.setText("Pengajuan PKL");

        jBtnAbsensi.setText("Absensi");

        jBtInformasi.setText("Informasi");

        jBtnLogout.setText("Logout");

        jLabelSelamatDatang.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSelamatDatang.setText("Selamat Datang ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(442, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtInformasi, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnPengajuanPkl, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(376, 376, 376))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelSelamatDatang, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabelSelamatDatang, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181)
                .addComponent(jBtnPengajuanPkl)
                .addGap(18, 18, 18)
                .addComponent(jBtnAbsensi)
                .addGap(18, 18, 18)
                .addComponent(jBtInformasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                .addComponent(jBtnLogout)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashboardSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashboardSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashboardSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashboardSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DashboardSiswa().setVisible(true);
//            }
//        });
//    }

    public JButton getjBtInformasi() {
        return jBtInformasi;
    }

    public void setjBtInformasi(JButton jBtInformasi) {
        this.jBtInformasi = jBtInformasi;
    }

    public JButton getjBtnAbsensi() {
        return jBtnAbsensi;
    }

    public JButton getjBtnLogout() {
        return jBtnLogout;
    }

    public void setjBtnLogout(JButton jBtnLogout) {
        this.jBtnLogout = jBtnLogout;
    }

    public JLabel getjLabelSelamatDatang() {
        return jLabelSelamatDatang;
    }

    public void setjLabelSelamatDatang(JLabel jLabelSelamatDatang) {
        this.jLabelSelamatDatang = jLabelSelamatDatang;
    }

    public void setjBtnAbsensi(JButton jBtnAbsensi) {
        this.jBtnAbsensi = jBtnAbsensi;
    }

    public JButton getjBtnPengajuanPkl() {
        return jBtnPengajuanPkl;
    }

    public void setjBtnPengajuanPkl(JButton jBtnPengajuanPkl) {
        this.jBtnPengajuanPkl = jBtnPengajuanPkl;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtInformasi;
    private javax.swing.JButton jBtnAbsensi;
    private javax.swing.JButton jBtnLogout;
    private javax.swing.JButton jBtnPengajuanPkl;
    private javax.swing.JLabel jLabelSelamatDatang;
    // End of variables declaration//GEN-END:variables
}
