/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projecttubesstrukturdatasiapraja.View.Admin;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Pongo
 */
public class DashboardAdminView extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnDataSiswa = new javax.swing.JButton();
        jBtnDataGuru = new javax.swing.JButton();
        jBtnDataInstansi = new javax.swing.JButton();
        jBtnDataMonitoring = new javax.swing.JButton();
        jBtnDataUser = new javax.swing.JButton();
        jBtnLogout = new javax.swing.JButton();
        jLabelSelamatDatang = new javax.swing.JLabel();
        jBtnDataPengajuan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnDataSiswa.setText("Data Siswa");

        jBtnDataGuru.setText("Data Guru");

        jBtnDataInstansi.setText("Data Instansi");

        jBtnDataMonitoring.setText("Data Monitoring");

        jBtnDataUser.setText("Data User");

        jBtnLogout.setText("Logout");

        jLabelSelamatDatang.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSelamatDatang.setText("Selamat Datang Admin");

        jBtnDataPengajuan.setText("Data Pengajuan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnDataUser, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnDataMonitoring, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnDataInstansi, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnDataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnDataPengajuan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelSelamatDatang, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelSelamatDatang, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jBtnDataSiswa)
                .addGap(18, 18, 18)
                .addComponent(jBtnDataGuru)
                .addGap(18, 18, 18)
                .addComponent(jBtnDataInstansi)
                .addGap(18, 18, 18)
                .addComponent(jBtnDataMonitoring)
                .addGap(18, 18, 18)
                .addComponent(jBtnDataUser)
                .addGap(18, 18, 18)
                .addComponent(jBtnDataPengajuan)
                .addGap(97, 97, 97)
                .addComponent(jBtnLogout)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DashboardAdmin().setVisible(true);
//            }
//        });
//    }

    public JButton getjBtnDataGuru() {
        return jBtnDataGuru;
    }

    public void setjBtnDataGuru(JButton jBtnDataGuru) {
        this.jBtnDataGuru = jBtnDataGuru;
    }

    public JButton getjBtnDataInstansi() {
        return jBtnDataInstansi;
    }

    public void setjBtnDataInstansi(JButton jBtnDataInstansi) {
        this.jBtnDataInstansi = jBtnDataInstansi;
    }

    public JButton getjBtnDataMonitoring() {
        return jBtnDataMonitoring;
    }

    public void setjBtnDataMonitoring(JButton jBtnDataMonitoring) {
        this.jBtnDataMonitoring = jBtnDataMonitoring;
    }

    public JButton getjBtnDataSiswa() {
        return jBtnDataSiswa;
    }

    public void setjBtnDataSiswa(JButton jBtnDataSiswa) {
        this.jBtnDataSiswa = jBtnDataSiswa;
    }

    public JButton getjBtnDataUser() {
        return jBtnDataUser;
    }

    public void setjBtnDataUser(JButton jBtnDataUser) {
        this.jBtnDataUser = jBtnDataUser;
    }

    public JButton getjBtnDataPengajuan() {
        return jBtnDataPengajuan;
    }

    public void setjBtnDataPengajuan(JButton jBtnDataPengajuan) {
        this.jBtnDataPengajuan = jBtnDataPengajuan;
    }

    public JButton getjBtnLogout() {
        return jBtnLogout;
    }

    public void setjBtnLogout(JButton jBtnLogout) {
        this.jBtnLogout = jBtnLogout;
    }

    public JLabel getjLabelSelamatDatang() {
        return jLabelSelamatDatang;
    }

    public void setjLabelSelamatDatang(JLabel jLabelSelamatDatang) {
        this.jLabelSelamatDatang = jLabelSelamatDatang;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDataGuru;
    private javax.swing.JButton jBtnDataInstansi;
    private javax.swing.JButton jBtnDataMonitoring;
    private javax.swing.JButton jBtnDataPengajuan;
    private javax.swing.JButton jBtnDataSiswa;
    private javax.swing.JButton jBtnDataUser;
    private javax.swing.JButton jBtnLogout;
    private javax.swing.JLabel jLabelSelamatDatang;
    // End of variables declaration//GEN-END:variables
}
